
import Navbar from "@/components/nav";
import './styles.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#0D1117]">
      <Navbar ></Navbar>  
      {children}   
      </body>
    </html>
  )
}
